//fix
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOADED = 'AUTH_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_LOADED = 'REGISTER_LOADED';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_LOADED = 'LOGIN_LOADED';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const GET_PENDING_FRIEND_LOADING = 'GET_PENDING_FRIEND_LOADING';
export const GET_PENDING_FRIEND_LOADED = 'GET_PENDING_FRIEND_LOADED';
export const GET_PENDING_FRIEND_ERROR = 'GET_PENDING_FRIEND_ERROR';

export const GET_USER_FRIEND_LOADING = 'GET_USER_FRIEND_LOADING';
export const GET_USER_FRIEND_LOADED = 'GET_USER_FRIEND_LOADED';
export const GET_USER_FRIEND_ERROR = 'GET_USER_FRIEND_ERROR';

export const ADD_FRIEND_LOADING = 'ADD_FRIEND_LOADING';
export const ADD_FRIEND_LOADED = 'ADD_FRIEND_LOADED';
export const ADD_FRIEND_ERROR = 'ADD_FRIEND_ERROR';

export const GET_FRIEND_LOADING = 'GET_FRIEND_LOADING';
export const GET_FRIEND_LOADED = 'GET_FRIEND_LOADED';
export const GET_FRIEND_ERROR = 'GET_FRIEND_ERROR';

export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_LOADED = 'GET_POSTS_LOADED';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_POSTS_LOADING = 'CREATE_POSTS_LOADING';
export const CREATE_POSTS_LOADED = 'CREATE_POSTS_LOADED';

export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING';
export const UPDATE_PROFILE_LOADED = 'UPDATE_PROFILE_LOADED';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

export const UPLOAD_AVATAR_LOADING = 'UPLOAD_AVATAR_LOADING';
export const UPLOAD_AVATAR_LOADED = 'UPLOAD_AVATAR_LOADED';
export const UPLODA_AVARAT_ERROR = 'UPLODA_AVARAT_ERROR';

export const GET_POSTS_MORE_LOADING = 'GET_POSTS_MORE_LOADING';
export const GET_POSTS_MORE_LOADED = 'GET_POSTS_MORE_LOADED';

export const GET_SUGESTION_LOADING = 'GET_SUGESTION_LOADING';
export const GET_SUGESTION_LOADED = 'GET_SUGESTION_LOADED';

// acak acakan
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const USER_LOADED = 'USER_LOADED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_PENDING_FRIEND = 'GET_PENDING_FRIEND';
export const GET_USER_FRIEND = 'GET_USER_FRIEND';
export const ADD_FRIEND = 'ADD_FRIEND';

export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const POST_ERROR = 'POST_ERROR';
export const DELETE_POST = 'DELETE_POST';
export const ADD_POST = 'ADD_POST';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const UPDATE_LIKES = 'UPDATE_LIKES';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
